Card wizard
neuefische/muc-22-2-team-harry-potter pull request #23
Opened 2022-12-01 14:23 UTC by KAMA-Kasckak-Martin

2022-12-01 14:28 UTC, KAMA-Kasckak-Martin commented on frontend/src/hooks/useWizards.ts
> +        return axios.post("wizard-students", newWizard)
delete this line

2022-12-01 14:34 UTC, KAMA-Kasckak-Martin reviewed
fixed code duplication

2022-12-01 15:20 UTC, s-gbz requested changes
Please finish the character saving functionality

2022-12-01 15:20 UTC, s-gbz commented on frontend/src/components/WizardApp.tsx
> +    const wizard:Wizard = {
What is the purpose of this wizzard object?

2022-12-01 15:20 UTC, s-gbz commented on frontend/src/components/WizardCard.scss
> +@import url('https://fonts.cdnfonts.com/css/harry-potter');
In the future it would be great to have this locally

2022-12-02 13:21 UTC, licetrosales approved these changes

2022-12-02 13:44 UTC, KAMA-Kasckak-Martin reviewed
bla bla

2022-12-02 13:45 UTC, merged